#!/usr/bin/env bash
# pdlcflow interactive setup — prompts only for the choices that need a human,
# defaults everything else, generates strong secrets, and writes .env. No
# hand-editing required. Re-run any time (confirms before overwriting .env).
set -euo pipefail

here="$(cd "$(dirname "$0")" && pwd)"
envfile="$here/.env"

# ── pdlcflow banner (mirrors upstream pdlc) ──────────────────────────────────
banner() {
  local C=$'\033[1;36m' R=$'\033[0m' Wh=$'\033[1;37m' Sub=$'\033[1;31m'
  local g1=$'\033[38;5;33m' g2=$'\033[38;5;39m' g3=$'\033[38;5;44m' g4=$'\033[38;5;49m'
  local W=46 bar; bar="$(printf '═%.0s' $(seq "$W"))"
  _row() { local t="$1" col="$2" len gap l r; len=${#t}; gap=$((W-len)); ((gap<0))&&gap=0; l=$((gap/2)); r=$((gap-l))
           printf "${C}║${R}${col}%*s%s%*s${R}${C}║${R}\n" "$l" "" "$t" "$r" ""; }
  printf "\n${C}╔%s╗${R}\n" "$bar"
  _row "" ""
  _row "██████  ██████  ██      ██████" "$g1"
  _row "██   ██ ██   ██ ██     ██     " "$g2"
  _row "██████  ██   ██ ██     ██     " "$g3"
  _row "██      ██   ██ ██     ██     " "$g3"
  _row "██      ██████  ██████  ██████" "$g4"
  _row "" ""
  _row "pdlcflow${1:+ v$1}" "$Wh"
  _row "Product Development Lifecycle" "$Sub"
  _row "" ""
  printf "${C}╚%s╝${R}\n\n" "$bar"
}

say() { printf '\033[1;36m%s\033[0m\n' "$*"; }
ask() { local p="$1" d="${2:-}" a; if [ -n "$d" ]; then read -r -p "$p [$d]: " a; echo "${a:-$d}"; else read -r -p "$p: " a; echo "$a"; fi; }
yn()  { local a; a="$(ask "$1 (y/n)" "${2:-n}")"; [[ "$a" =~ ^[Yy] ]]; }
secret() { openssl rand -hex 24 2>/dev/null || head -c24 /dev/urandom | base64 | tr -dc 'a-zA-Z0-9' | head -c32; }

banner "${PDLCFLOW_VERSION:-}"

if [ -f "$envfile" ]; then
  yn "$envfile exists — overwrite?" n || { echo "Keeping existing .env. Run: docker compose up -d"; exit 0; }
fi

say "Setup — press Enter to accept the [default]."
version="$(ask "Image version to run" "latest")"
pg_pw="$(secret)"; app_pw="$(secret)"; jwt="$(secret)"

auth=false; boot_email=""; boot_pw=""
if yn "Require login (multi-tenant auth + RLS)?" n; then
  auth=true
  boot_email="$(ask "Bootstrap admin email" "admin@example.com")"
  boot_pw="$(ask "Bootstrap admin password (Enter = generate)" "")"
  [ -z "$boot_pw" ] && boot_pw="$(secret)" && say "  generated admin password: $boot_pw"
fi

wire_llm=false; provider="bedrock"; declare -a creds=()
if yn "Use real LLM models now (else offline stub)?" n; then
  wire_llm=true
  provider="$(ask "Provider (bedrock|anthropic|openai|gemini|azure|vertex|ollama)" "bedrock")"
  case "$provider" in
    bedrock)   creds+=("AWS_ACCESS_KEY_ID=$(ask 'AWS_ACCESS_KEY_ID' '')")
               creds+=("AWS_SECRET_ACCESS_KEY=$(ask 'AWS_SECRET_ACCESS_KEY' '')")
               creds+=("AWS_REGION=$(ask 'AWS_REGION' 'us-east-1')") ;;
    anthropic) creds+=("ANTHROPIC_API_KEY=$(ask 'ANTHROPIC_API_KEY' '')") ;;
    openai)    creds+=("OPENAI_API_KEY=$(ask 'OPENAI_API_KEY' '')") ;;
    gemini)    creds+=("GOOGLE_API_KEY=$(ask 'GOOGLE_API_KEY' '')") ;;
    azure)     creds+=("AZURE_OPENAI_API_KEY=$(ask 'AZURE_OPENAI_API_KEY' '')")
               creds+=("AZURE_OPENAI_ENDPOINT=$(ask 'AZURE_OPENAI_ENDPOINT (https://<res>.openai.azure.com)' '')") ;;
    vertex)    creds+=("GOOGLE_APPLICATION_CREDENTIALS=$(ask 'Path to GCP service-account JSON (or use workload identity)' '')")
               creds+=("GOOGLE_CLOUD_PROJECT=$(ask 'GOOGLE_CLOUD_PROJECT' '')")
               creds+=("GOOGLE_CLOUD_REGION=$(ask 'GOOGLE_CLOUD_REGION' 'us-east5')") ;;
    ollama)    creds+=("PDLC_OLLAMA_ENDPOINT=$(ask 'Ollama endpoint' 'http://localhost:11434')") ;;
    *)         say "  unknown provider — add its credentials to .env manually." ;;
  esac
fi

run_evals=false
yn "Run evals (scores agent output; uses judge LLM calls when LLM is on)?" n && run_evals=true

{
  echo "# Generated by setup.sh — re-run to regenerate."
  echo "PDLCFLOW_VERSION=$version"
  echo "POSTGRES_PASSWORD=${pg_pw}"
  echo "PDLC_APP_DB_PASSWORD=${app_pw}"
  echo "PDLC_DB_URL=postgresql+asyncpg://pdlc_app:${app_pw}@postgres:5432/pdlc"
  echo "PDLC_MIGRATION_DB_URL=postgresql+asyncpg://postgres:${pg_pw}@postgres:5432/pdlc"
  echo "PDLC_REDIS_URL=redis://redis:6379/0"
  echo "PDLC_USE_POSTGRES_CHECKPOINTER=true"
  echo "PDLC_USE_REDIS_BUS=true"
  echo "PDLC_ARTIFACT_STORE=filesystem"
  echo "PDLC_ARTIFACT_DIR=/var/lib/pdlcflow/artifacts"
  echo "PDLC_TASK_STORE=postgres"
  echo "PDLC_ANALYTICS_BACKEND=postgres"
  echo "PDLC_CLICKSTREAM_SINK=postgres"
  echo "PDLC_STREAM_TOKENS=true"
  echo "PDLC_AUTH_REQUIRED=${auth}"
  echo "PDLC_AUTH_MODE=local"
  echo "PDLC_JWT_SECRET=${jwt}"
  [ -n "$boot_email" ] && echo "PDLC_BOOTSTRAP_ADMIN_EMAIL=${boot_email}"
  [ -n "$boot_pw" ] && echo "PDLC_BOOTSTRAP_ADMIN_PASSWORD=${boot_pw}"
  echo "PDLC_WIRE_LLM=${wire_llm}"
  echo "PDLC_DEFAULT_LLM_PROVIDER=${provider}"
  echo "PDLC_JUDGE_TIER=premium"
  echo "PDLC_RUN_EVALS=${run_evals}"
  echo "PDLC_EVAL_BLOCKING="
  for c in "${creds[@]:-}"; do [ -n "$c" ] && echo "$c"; done
} > "$envfile"

say "Wrote $envfile"
echo
echo "Next:"
echo "  docker compose up -d"
echo "  docker compose run --rm api uv run alembic upgrade head"
echo "  open http://localhost:8080   (Studio)   ·   http://localhost:8000/health   (API)"
if [ "$auth" = true ]; then echo "  sign in as ${boot_email}"; fi
