"""PDLC clickstream event schema — envelope + 37 typed payloads.

Public API is the EventEnvelope plus the typed payload classes per event type.
The taxonomy and rationale live in registry.md.
"""

from .envelope import EventEnvelope, EVENT_TYPES
from .payloads import (
    SessionOpenedPayload,
    SessionResumedPayload,
    SessionClosedPayload,
    PhaseEnteredPayload,
    PhaseExitedPayload,
    PhaseTransitionPayload,
    SubphaseEnteredPayload,
    SubphaseExitedPayload,
    StepCompletedPayload,
    SkillInvokedPayload,
    AgentInvokedPayload,
    AgentRespondedPayload,
    GateOpenedPayload,
    GateResolvedPayload,
    PartyOpenedPayload,
    PartyPitchReceivedPayload,
    PartyConsensusReachedPayload,
    ToolInvokedPayload,
    ToolBlockedPayload,
    TestRunPayload,
    TestPassedPayload,
    TestFailedPayload,
    StrikeRecordedPayload,
    StrikePanelConvenedPayload,
    DeployRequestedPayload,
    DeploySucceededPayload,
    DeployBlockedPayload,
    NightShiftStartedPayload,
    NightShiftVerdictPayload,
    NightShiftCompletedPayload,
    NightShiftAbortedPayload,
    DecisionRecordedPayload,
    OverrideInvokedPayload,
    LLMTokensSpentPayload,
    ContextWarningPayload,
    UIViewedPayload,
    ErrorPayload,
)

__all__ = [
    "EventEnvelope",
    "EVENT_TYPES",
    "SessionOpenedPayload",
    "SessionResumedPayload",
    "SessionClosedPayload",
    "PhaseEnteredPayload",
    "PhaseExitedPayload",
    "PhaseTransitionPayload",
    "SubphaseEnteredPayload",
    "SubphaseExitedPayload",
    "StepCompletedPayload",
    "SkillInvokedPayload",
    "AgentInvokedPayload",
    "AgentRespondedPayload",
    "GateOpenedPayload",
    "GateResolvedPayload",
    "PartyOpenedPayload",
    "PartyPitchReceivedPayload",
    "PartyConsensusReachedPayload",
    "ToolInvokedPayload",
    "ToolBlockedPayload",
    "TestRunPayload",
    "TestPassedPayload",
    "TestFailedPayload",
    "StrikeRecordedPayload",
    "StrikePanelConvenedPayload",
    "DeployRequestedPayload",
    "DeploySucceededPayload",
    "DeployBlockedPayload",
    "NightShiftStartedPayload",
    "NightShiftVerdictPayload",
    "NightShiftCompletedPayload",
    "NightShiftAbortedPayload",
    "DecisionRecordedPayload",
    "OverrideInvokedPayload",
    "LLMTokensSpentPayload",
    "ContextWarningPayload",
    "UIViewedPayload",
    "ErrorPayload",
]
