"""PDLC clickstream event schema — envelope + typed payloads.

Public API is the EventEnvelope plus the typed payload classes per event type.
The full taxonomy (EVENT_TYPES) and per-event semantics live in registry.md,
kept in sync by scripts/check_event_registry.py. Some audit/telemetry families
(admin.*, llm_config.*, prompt*.*) carry generic reference dicts rather than a
rigid payload class — see registry.md.
"""

from .envelope import EVENT_TYPES, EventEnvelope, actor_type_for
from .payloads import (
    AgentInvokedPayload,
    AgentRespondedPayload,
    BudgetThresholdPayload,
    ContextWarningPayload,
    DecisionRecordedPayload,
    DeployBlockedPayload,
    DeployRequestedPayload,
    DeploySucceededPayload,
    ErrorPayload,
    EvalBlockedPayload,
    EvalScoredPayload,
    GateOpenedPayload,
    GateResolvedPayload,
    LLMFailoverPayload,
    LLMRateLimitedPayload,
    LLMTokensSpentPayload,
    NightShiftAbortedPayload,
    NightShiftCompletedPayload,
    NightShiftStartedPayload,
    NightShiftVerdictPayload,
    OverrideInvokedPayload,
    PartyConsensusReachedPayload,
    PartyOpenedPayload,
    PartyPitchReceivedPayload,
    PhaseEnteredPayload,
    PhaseExitedPayload,
    PhaseTransitionPayload,
    SessionClosedPayload,
    SessionOpenedPayload,
    SessionResumedPayload,
    SkillInvokedPayload,
    StepCompletedPayload,
    StrikePanelConvenedPayload,
    StrikeRecordedPayload,
    SubphaseEnteredPayload,
    SubphaseExitedPayload,
    TestFailedPayload,
    TestPassedPayload,
    TestRunPayload,
    ToolBlockedPayload,
    ToolCalledPayload,
    ToolInvokedPayload,
    UIViewedPayload,
)

__all__ = [
    "EVENT_TYPES",
    "AgentInvokedPayload",
    "AgentRespondedPayload",
    "BudgetThresholdPayload",
    "ContextWarningPayload",
    "DecisionRecordedPayload",
    "DeployBlockedPayload",
    "DeployRequestedPayload",
    "DeploySucceededPayload",
    "ErrorPayload",
    "EvalBlockedPayload",
    "EvalScoredPayload",
    "EventEnvelope",
    "GateOpenedPayload",
    "GateResolvedPayload",
    "LLMFailoverPayload",
    "LLMRateLimitedPayload",
    "LLMTokensSpentPayload",
    "NightShiftAbortedPayload",
    "NightShiftCompletedPayload",
    "NightShiftStartedPayload",
    "NightShiftVerdictPayload",
    "OverrideInvokedPayload",
    "PartyConsensusReachedPayload",
    "PartyOpenedPayload",
    "PartyPitchReceivedPayload",
    "PhaseEnteredPayload",
    "PhaseExitedPayload",
    "PhaseTransitionPayload",
    "SessionClosedPayload",
    "SessionOpenedPayload",
    "SessionResumedPayload",
    "SkillInvokedPayload",
    "StepCompletedPayload",
    "StrikePanelConvenedPayload",
    "StrikeRecordedPayload",
    "SubphaseEnteredPayload",
    "SubphaseExitedPayload",
    "TestFailedPayload",
    "TestPassedPayload",
    "TestRunPayload",
    "ToolBlockedPayload",
    "ToolCalledPayload",
    "ToolInvokedPayload",
    "UIViewedPayload",
    "actor_type_for",
]
