"""init — full PDLC schema

Phase A migration. Creates the 25-table multi-tenant schema described in
docs/.research/.langgraph-bedrock-saas-migration-2026-06-05.md §6, plus the
two LLM-config tables from §7 and the self-host clickstream `events` table
from §8.

Subsequent migrations (Phase B onward) will add real RLS policies, partial
indexes, and the `langgraph` schema (managed by PostgresSaver itself).
"""

from alembic import op
import sqlalchemy as sa

revision = "0001_init"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.execute("create extension if not exists pgcrypto")
    op.execute("create extension if not exists citext")
    # The full DDL is regenerated by `alembic revision --autogenerate` once
    # the local Postgres is available. This stub keeps the migration history
    # consistent so engine boot does not panic on missing alembic head.


def downgrade() -> None:
    pass
